export const GET_PRODUCTS_REQUESTED = "GET_PRODUCTS_REQUESTED";
export const GET_PRODUCTS_SUCCESS = "GET_PRODUCTS_SUCCESS";
export const GET_PRODUCTS_FAILED = "GET_PRODUCTS_FAILED";

export const POST_PRODUCTS_REQUESTED = "POST_PRODUCTS_REQUESTED";
export const POST_PRODUCTS_SUCCESS = "POST_PRODUCTS_SUCCESS";
export const POST_PRODUCTS_FAILED = "POST_PRODUCTS_FAILED";

export const PUT_PRODUCT_REQUESTED = "PUT_PRODUCT_REQUESTED";
export const PUT_PRODUCT_SUCCESS = "PUT_PRODUCT_SUCCESS";
export const PUT_PRODUCT_FAILED = "PUT_PRODUCT_FAILED";

export const DELETE_PRODUCT_REQUESTED = "DELETE_PRODUCT_REQUESTED";
export const DELETE_PRODUCT_SUCCESS = "DELETE_PRODUCT_SUCCESS";
export const DELETE_PRODUCT_FAILED = "DELETE_PRODUCT_FAILED";

export const GET_PRODUCT_REQUESTED = "GET_PRODUCT_REQUESTED";
export const GET_PRODUCT_SUCCESS = "GET_PRODUCT_SUCCESS";
export const GET_PRODUCT_FAILED = "GET_PRODUCT_FAILED";

export const PUT_FORM_ADMIN_STATE = "PUT_FORM_ADMIN_STATE";
export const FORM_ADMIN_EDITING_STATE = "FORM_ADMIN_EDITING_STATE";

export const GET_BUYS_REQUESTED = "GET_BUYS_REQUESTED";
export const GET_BUYS_SUCCESS = "GET_BUYS_SUCCESS";
export const GET_BUYS_FAILED = "GET_BUYS_FAILED";

export const POST_BUY_REQUESTED = "POST_BUY_REQUESTED";
export const POST_BUY_SUCCESS = "POST_BUY_SUCCESS";
export const POST_BUY_FAILED = "POST_BUY_FAILED";

export const SIGNIN_REQUESTED = "SIGNIN_REQUESTED";
export const SIGNIN_SUCCESS = "SIGNIN_SUCCESS";
export const SIGNIN_FAILED = "SIGNIN_FAILED";
export const SIGNOUT = "SIGNOUT";

export const TOOGLE_MODAL = "TOOGLE_MODAL";
export const TOOGLE_LOGIN = "CLOSE_LOGIN";
export const TOOGLE_BUYED = "TOOGLE_BUYED";

export const PRODUCT_MODAL_DELETE = "PRODUCT_MODAL_DELETE";
