export const GET_PRODUCTS_REQUESTED = "GET_PRODUCTS_REQUESTED";
export const GET_PRODUCTS_SUCCESS = "GET_PRODUCTS_SUCCESS";
export const GET_PRODUCTS_FAILED = "GET_PRODUCTS_FAILED";

export const POST_PRODUCTS_REQUESTED = "POST_PRODUCTS_REQUESTED";
export const POST_PRODUCTS_SUCCESS = "POST_PRODUCTS_SUCCESS";
export const POST_PRODUCTS_FAILED = "POST_PRODUCTS_FAILED";

export const PUT_PRODUCT_REQUESTED = "PUT_PRODUCT_REQUESTED";
export const PUT_PRODUCT_SUCCESS = "PUT_PRODUCT_SUCCESS";
export const PUT_PRODUCT_FAILED = "PUT_PRODUCT_FAILED";

export const DELETE_PRODUCT_REQUESTED = "DELETE_PRODUCT_REQUESTED";
export const DELETE_PRODUCT_SUCCESS = "DELETE_PRODUCT_SUCCESS";
export const DELETE_PRODUCT_FAILED = "DELETE_PRODUCT_FAILED";

export const PUT_FORM_ADMIN_STATE = "PUT_FORM_ADMIN_STATE";
export const FORM_ADMIN_EDITING_STATE = "FORM_ADMIN_EDITING_STATE";

export const BUY_PRODUCT_REQUESTED = "BUY_PRODUCT_REQUESTED";
export const BUY_PRODUCT_SUCCESS = "BUY_PRODUCT_SUCCESS";
export const BUY_PRODUCT_FAILED = "BUY_PRODUCT_FAILED";
